name: Unit Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  unit-test:
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-24.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: setup for public beta of Ubuntu 24.04
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
    - name: Install GNU Getopt on macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install gnu-getopt
    - name: configure
      run: ./configure --with-cxx=clang++
    - name: build
      run: make
    - name: check
      run: make check
